language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: "KYzK5brx7gSNV8SdX/uDei0Vh62AvpbhEPLkJKD4BG+o4lNMPWgLucnPRyCBDZ6xpWHZgwU8cEp6fKW/8tJQXouXLjO2hmuabxcc0JN1fFiCrZlxAoPmT2l6CPAuD1YTeNgP7rztOj9OGZeO2WwYGOJTfQE3bJxbOAaixWDUbQ7rhsEAOxQMCLENGnpnRiR/9+/7c8brSiBJ9AJnSNZJ2wCFBxrjsA9NV1S1dfsEJ+m1BAj1Xtq8VHX/lMF/gUuz0iqucmImwxfXKS0LDSlEm0NZXYFSkCWaTIKvOBcOf2QkLzT1DJ17vgk5fFnKGpuiBBhYDbOspHNVaCpETDB9zRpjmkHsBipwof7KrgGPxJ7tFp0cDO/c22RyZRywHoQtavk/SpBSlqp4iNvAOuwAR4AE86ucX92oIQElO+ergiW+AhfHJAEiq+v4kQzBDp5lQdcXGD6vPi/h4iF7J4wzGzh+/2x/9MPuacwvyxex1zjgKrCm85wvoWfXEY2r1srpvFNCi/GJvE/AEsVERjOKoSujBhYXi6u02x9OCITT9JalrBw3Wx7a919k7PhCFoUVWLtWgRuZBYwU8is+O6+jgjyB8oqHGGHPT2vbfWgoqvyxUK2NAPLnHKtQ8wE7Vv5PPNIdbairRYp8UclJYKcxWVXmfIkLh/XChfVL1QaP8CQ="
  app: frozen-escarpment-63947
  on:
    repo: emily-morris/node-capstone
